version: '3.9'

services:
  yolo-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app

  backend:
    build:
      context: ./smartuseme-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - yolo-api
    environment:
      FLASK_API_URL: http://yolo-api:5000

  frontend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    command: python -m http.server 5500
    ports:
      - "5500:5500"
    depends_on:
      - backend